### PR TITLE
 Fix GH#16227: MusicXML export is incorrect when using local timsig

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Backport of #23255

Resolves: [musescore#16227](https://www.github.com/musescore/MuseScore/issues/16227)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Hmm, I don't understand those failing mtests, @lvinken?

**Comment by lvinken** [comment]
Will have a look, may take a few days.

**Comment by lvinken** [comment]
Root cause found for the backup duration issue (one moveToTick() is missing), working on a fix.

**Comment by Jojo-Schmitz** [comment]
Is it your changes in `ExportMusicXml::writeMeasureStaves()`? For those I didn'd find a counterpart in 3.x

**Comment by lvinken** [comment]
Yes, I think that is indeed the root cause. The fix is below. The issue with testLocalTimeSig14 I cannot yet explain.

diff --git a/importexport/musicxml/exportxml.cpp b/importexport/musicxml/exportxml.cpp
index b6e8b4f69c..b54e106682 100644
--- a/importexport/musicxml/exportxml.cpp
+++ b/importexport/musicxml/exportxml.cpp
@@ -2043,7 +2043,7 @@ void ExportMusicXml::moveToTick(const Fraction& t, const Fraction& stretch)
       Fraction stretchedM_tick { t + stretch * (tick() - t) };
 #ifdef DEBUG_TICK
       qDebug() << "t (target) " << fractionToQString(t) << " stretch " << fractionToQString(stretch)
-               << " _tick (current) " << fractionToQString(_tick) << " stretchedM_tick " << fractionToQString(stretched_tick);
+               << " _tick (current) " << fractionToQString(_tick) << " stretchedM_tick " << fractionToQString(stretchedM_tick);
 #endif
       if (t < _tick) {
 #ifdef DEBUG_TICK
@@ -7316,6 +7316,12 @@ void ExportMusicXml::writeMeasureTracks(const Measure* const m,
 
                   } // for (Segment* seg = ...
             _attr.stop(_xml);
+            const bool isLastVoiceOfStaff = st % VOICES == VOICES - 1;
+            const bool isLastVoiceOfLastStaff = st == etrack - 1;
+            if (isLastVoiceOfStaff && !isLastVoiceOfLastStaff) {
+                  // move tick to start of measure, generates backup to next staff, needs this staff's stretch
+                  moveToTick(m->tick(), stretch(_score, st, m->tick()));
+                  }
             } // for (int st = ...
       }

**Comment by lvinken** [comment]
Hmm, pasting a diff does not really work well :-(

**Comment by Jojo-Schmitz** [comment]
I fixed it

**Comment by Jojo-Schmitz** [comment]
It seems testLocalTimeSig14 fails because 3.x doesn't (yet) export "measure-repeat".
Would need to find now which PR added that to Mu4...

**Pull request merged**
