### PR TITLE
Fix GH#25204: Color of instruments not respected

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Backport of #25606 plus fixing a clazy warning

Resolves: [musescore#25204](https://www.github.com/musescore/MuseScore/issues/25204)

For some strange reason this doesn't seem to work though?!? Same code does work in Mu4...

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@krasko78 any idea why this doesn't work here?

**Comment by krasko78** [comment]
Hi Jojo, since this is 3.x, it would take me some time to set it up and find out but I downloaded this branch and compared the code with the code of 4.5.0 and didn't see any differences. Alll calls seem the same to me. Here is the stack trace that should lead to my change:

1. editstyle.cpp, line 694 : we listen for changes to the color of the text style
2. editstyle.cpp, line 1866 : `cs->undoChangeStyleVal(a.sid, value);`
3. edit.cpp, line 3864 : `undo(new ChangeStyleVal(this, idx, v));`
4. score.cpp, line 3776 : `undoStack()->push(cmd, ed);`
5. undo.cpp, line 298 : `cmd->redo(ed);`
6. undo.cpp, line 156 : `flip(ed);`
7. undo.cpp, line 1733 : `score->styleChanged();`
8. score.cpp, line 1264 : `scanElements(0, updateStyle);`
9. score.cpp, line 1854 : `s->scanElements(data, func, all);`
10. system.cpp, line 1252 : `func(data, t);`
11. score.cpp, line 1253 : e->styleChanged();
12. textbase.cpo, line 3002 : `setProperty(spp.pid, safePropertyStyleValue(spp.pid));`
13. and we arrive to iname.cpp, line 142 where my change is. It should enter the `default` clause of the `switch` and call `TextBase::setProperty(id, v);` on line 153 for the color to get updated.

If it does not work in 3.x, my assumption is somewhere along this chain something happens and the chain does not execute to the end. Since you have 3.x set up, try debugging this chain and see what's going on. Let me know if this helps.

**Comment by Jojo-Schmitz** [comment]
In Mu3 `TextBase::setProperty()` doesn't set the color itself, but lets `Element::setProperty()` do it. (Haven't check Mu4's code on this yet)
But it doesn't work regardless.
Not even when copying 
```cpp
            case Pid::COLOR:
                  setColor(v.value<QColor>());
                  break;
```
into iname.cpp`s `InstrumentName::setProperty()` or textbase.cpp's `TextBase::setProperty()`

**Comment by Jojo-Schmitz** [comment]
But in the mscz/mscx the color is getting set, it does show in Format > Style > Textstyles > Instrumentname long/short > Color

**Comment by krasko78** [comment]
_"In Mu3 TextBase::setProperty() doesn't set the color itself, but lets Element::setProperty() do it. (Haven't check Mu4's code on this yet)"_ - Yes, it is the same in MU4

So you debugged and `InstrumentName::setProperty()` does get hit? And it does not work even if the file is saved, closed and reopened?

Where can I find the most up-to-date instructions on how to set up MuseScore 3 to compile and run in Qt Creator?

**Comment by Jojo-Schmitz** [comment]
The getter and setter do get hit.

I believe the development instructions in the developers' handbook should still work on Mu3

**Comment by Jojo-Schmitz** [comment]
It's pretty hard for me so describe what it takes to build Mu3, as my setup hasn't changed in ages and I simply don't recall anymore what I had to do

**Comment by krasko78** [comment]
I am trying to set it up but am getting this error: 
`ninja: error: build.ninja:762: bad $-escape (literal $ must be written as $$)`

I have tried changing `$` to `$$` and `(` to `{` in `CreatePrecompilerHeader.cmake` and was able to get CMake to succeed but then I cannot build MuseScore due to this error: 
`C:\Users\krasko\Downloads\mscore3\thirdparty\beatroot\BeatTracker.cpp: fatal error C1083: Cannot open precompiled header file: 'C:/Users/krasko/Downloads/mscore3/builds/Desktop_Qt_5_15_2_MSVC2019_64bit-Debug/importexport/beatroot//all.pch': No such file or directory`

Obviously `$(Configuration)` is empty/undefined (note the two consecutive slashes) and the `all.pch` file does not get created. Any ideas?

**Comment by Jojo-Schmitz** [comment]
I believe I've never used Ninja

**Comment by Jojo-Schmitz** [comment]
But this `Desktop_Qt_5_15_2_MSVC2019_64bit-Debug` looks strange to me, I had it set to `build.qtc`

Hmm, are you using MinGW? I am (never got round to get MSVC builds running with Qt Ctreator)

**Comment by Jojo-Schmitz** [comment]
OTOH hand I can also build Mu3 in Visual Studio

**Comment by krasko78** [comment]
The `Desktop_bla_bla` folder is automatically created by Qt Creator, I have a very similar one for MU4 and have no issues. I use MSVC with Qt Creator and for MU4 it works relatively smoothly following the oficial instructions but for MU3 it does not want to play nice. Let me try downloading VS and see what happpens. Which version of VS do you use - 2019 or newer?

**Comment by Jojo-Schmitz** [comment]
2022

**Comment by Jojo-Schmitz** [comment]
Although withthe latest update (a couple days ago) that is broken too, I had to copy/rename 2 folders, C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433 to 14.41.34120 and C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.42.34433 to 14.40.33807

**Comment by krasko78** [comment]
Got it almost to compile in VS, the only errors are related to it not being able to open jack/jack.h. I didn't install JACK because the docs were saying it is only needed for MU 3.6.2 or earlier. What should I do?

**Comment by krasko78** [comment]
Never mind, installed JACK and i have it running!!!!! Hurrayyyyy!!!

**Comment by krasko78** [comment]
Found the problem:
image

This is in system.cpp, line 926 (inside `System::setInstrumentNames`): it creates the instrument (line 920), this gets the color from the style but then on 926 the color is replaced with some color that is taken from the part. If this line 926 is commented out, the color works.

It looks like this code is executed upon opening of the score (understandably) but also when the color is changed in the style because the score is updated and the `_systems.clear();` call on line 5310 of layout.cpp destroys all the systems which (in their destructor) destroy all of their staves. So the systems and staves are recreated and this code is executed. This explains why the color does not work neither on score open nor on style change.

**Comment by Jojo-Schmitz** [comment]
Great finding, thanks a lot!
Interesting ling that got add by me via 61bf8ec9 (porting a fix of @SKefalidis) to
 Fix [#12815](https://musescore.org/en/node/12815): Ability to change the color of instrument names individually
There though I mentioned that it doesn't work ?!?

**Comment by Jojo-Schmitz** [comment]
It does work, individually via staff properties (foe long andd short name together), just not as style settings

**Comment by Jojo-Schmitz** [comment]
Now the question is whether we can have both, a setting in staff properties and settings in text styles.
My attempt to do it like this failed:
```cpp
                        if (iname->getProperty(Pid::COLOR) != iname->propertyDefault(Pid::COLOR)) // changed style takes precedence
                              iname->setColor(part->namesColor(tick));
```

**Comment by krasko78** [comment]
Why do you want the style to take precedence? Shouldn't it be the other way around: the users will use the style to change all instrument names at once and then customize some colors individually through the staff properties?

**Comment by Jojo-Schmitz** [comment]
True. But both should work, not just one

**Comment by krasko78** [comment]
Yes, but in what order? I'd do it this way:

1. STYLE takes precedence over PART (what you have tried): If the style is set (i.e. is not black), color is taken from it regardless of the part:

```
                if (iname->propertyDefault(Pid::COLOR) == MScore::defaultStyle().value(iname->getPropertyStyle(Pid::COLOR))) // changed style takes precedence
                    iname->setColor(part->namesColor(tick));
```
2. PART takes precedence over STYLE: If the color on the part is set (i.e. is not black), the color is taken from it, otherwise from the style:

```
                QColor partColor = part->namesColor(tick);
                if (partColor != MScore::defaultColor)
                    iname->setColor(partColor);
```

To me #2 makes more sense...

**Comment by Jojo-Schmitz** [comment]
OK, let's take the latter.

**Pull request merged**
