### PR TITLE
[Cmd: insert/append measure] dialog should have spinbox highlighted by default ready for keyboard entry

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Replaces #614

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@worldwideweary fine by you?

**Comment by worldwideweary** [comment]
Hey man, if it works, it's fine by me. Looks ok too.

**Comment by Jojo-Schmitz** [comment]
Does it work for you, on Linux?

**Comment by worldwideweary** [comment]
Yeah, from my side it feels equivalent on my machine as to what I was getting on my PR

**Pull request merged**
