### PR TITLE
Fixed access keys in Japanese translation

### PR DESCRIPTION
**Pull request by bakajikara**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Thanks. I can't verify the correctness, so am taking your word for it 😉

**Comment by knoike** [comment]
https://github.com/Jojo-Schmitz/MuseScore/pull/184/files#diff-6e9875593fc5b32ca44d4768a99d9f408bd9436d0fca94b21e6b0c81424c7860R14373

About here.
I think the previous version is correct.
(音符(&amp;N) is correct. 音符(&amp;O) is wrong.)

**Comment by bakajikara** [comment]
You are right, that was my mistake actually. Corrected in #185

**Comment by Jojo-Schmitz** [comment]
Thanks, merged

**Pull request merged**
