### PR TITLE
Fix #445 - Horizontal View not resetting view on rewind

### LINKED ISSUE #445: Button "Rewind to beginning"
When the "Rewind to beginning" button is pressed, the view of the sheet of music no longer jumps to the beginning.

If you then press the Play button, the music is played from the beginning but the sheet of music is not tracked.

Jumping to the beginning is only possible with the "Pos1" button

Similar behavior exists in MS 4.x and is now also executed in MS 3.7

Is this behavior intentional?

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #445 

There probably is a more fundamental fix somewhere to be performed, but for now this should give appropriate rewinding in horizontal/vertical and also constrain for vertical as with #377 

Plz test ;)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Tested, does what it says on the tin ;-), thanks!

**Comment by worldwideweary** [comment]
Don't know if you get notifications on old merged issues, but I think it might be wise to revert the cx, cy argument list to take only cx and remove cy back to y while keeping everything else the exact same 

so this:
```cpp
setOffset(cx, y);
```
instead of setOffset(cx, cy);

with cx,cy under certain circumstances i'm getting whacky results towards the end of a score

[whacky.webm](https://github.com/user-attachments/assets/06c71460-1a9f-4615-ac09-f2c9df1ebf60)

Figured I'd mention it.

**Comment by Jojo-Schmitz** [comment]
I do get notifications...

**Comment by Jojo-Schmitz** [comment]
I don't quite get though what you mean, can you PR it please?

**Pull request merged**
