### PR TITLE
Raise GitHub CI build platform to macOS-13

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Sort of backporting #19570

macOS 12 will stop to work on GitHub CI by 3 Dec 2024, see https://github.com/actions/runner-images/issues/10721
Seems that measn we'd have to raise macOS **deployment target** to 10.13 too?

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Not the slightest idea why this happens
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LAME_INCLUDE_DIR
```

**Comment by Jojo-Schmitz** [comment]
OK, fixed the LAME issue, but now hitting
`error: Cycle in dependencies between targets 'audio' and 'awl'; building could produce unreliable results.`

**Comment by Jojo-Schmitz** [comment]
@cbjeukendrup any idea how to get this to work?

**Comment by cbjeukendrup** [comment]
It is not macOS 10.12 that was removed, but macOS 12.0. Also, the deployment target is the oldest OS that the app with _run_ on, not the oldest OS that it will _compile_ on.
So, updating the deployment target is not directly a logical thing to do, except if it turns out that Xcode 15 doesn't support deployment targets below 10.13 anymore.

Switching from `macOS-12` to `macOS-13` does involve an Xcode update: the default changes from Xcode 14.2 to Xcode 15.2, and some old versions were removed. Because of https://github.com/Jojo-Schmitz/MuseScore/blob/de7bb027b648d2fb689c8ebf2f44765c650e9350/.github/workflows/build_macos.yml#L38, you had previously pinned the Xcode version at 13.1, which is no longer provided with `macOS-13`, so therefore you're effectively jumping from 13.1 to 15.2.

With Xcode, there is something with a 'legacy build system' and a 'new build system'. With the 'new build system', the build has always failed, because of alleged dependency cycles. Therefore, we've always had to build the 3.x branch using the 'legacy build system'. But it turns out that that has been removed since Xcode 14.0, and older Xcode versions are not only not provided by GitHub Actions by default, but can also not be installed on macOS 13+ from other sources.

So, your only option is to sort out the dependency cycle, so that you can compile using the latest Xcode. Once that's sorted out, I think you can just switch to `macOS-latest` and don't specify any `DEVELOPER_DIR`, so that you stay on the latest version.

Or maybe there is one other option: use the Ninja generator instead of the Xcode generator (i.e. pass `-GNinja` to CMake). But I presume there was a reason that we didn't do that; probably it was because Ninja fails with the same dependency cycle.

If you're looking for example PRs that might help with that, you could look at the oldest PRs by Igor. Here are some that might be somehow related: 
https://github.com/musescore/MuseScore/pull/5945
https://github.com/musescore/MuseScore/pull/7014
and many more, see for example this query: https://github.com/musescore/MuseScore/pulls?page=1&q=is%3Apr+is%3Amerged+author%3Aigorkorsukov+cmake

**Comment by cbjeukendrup** [comment]
As a Christmas gift, [here is a branch](https://github.com/cbjeukendrup/MuseScore/tree/refs/heads/asdfghjkl) that [seems to build successfully](https://github.com/cbjeukendrup/MuseScore/actions/runs/12474237644).

**Comment by Jojo-Schmitz** [comment]
Thanks a lot and Merry Christmas!

**Pull request merged**
