### PR TITLE
[Cmd: Paste Clone] insert cloned measure bases via shortcut or right-…

### PR DESCRIPTION
**Pull request by worldwideweary**
…click score menu

Frames work with regular copy paste (as insertion, not appending) [Keysig/Timesig/Clef] Copied before performing
[Score to score]
V/H/T Boxes to allow copy-drag to clone. Also work as regular copy/paste since they didn't do anything beforehand

Resolves/relates:  #638

Probably will want to link this to the .org forums to get some 3.7 users to test it out and give feedback or find undesirable behavior or crashes so I can work them out further. 

Once again:
Cloning occurs before selection as an insert
Shift+Ctrl+Drag allows cloning frames, even text frames.
Some "undesirable" behavior is inevitable because clefs can be from a measure "before" the range selection, and things of that sort, but I tried to keep it within a reasonable default.

### CODE REVIEW

**Comment by worldwideweary** [comment]
Apparently I'm using "variable length array" in Linux and MSVC isn't having it. Will redo sometime soon. 
The irony that Microsoft is the one using more "standard" language is hittin' me.

**Comment by Jojo-Schmitz** [comment]
There are enough examples in the code on how to do it for MSVC

**Comment by worldwideweary** [comment]
I'll just switch to standard vectors: that should do it for now

**Comment by Jojo-Schmitz** [comment]
Can you rebase,? The old artifacts expired...

**Comment by Jojo-Schmitz** [comment]
What the heck, I'll just merge it ;-)

**Comment by worldwideweary** [comment]
For what it's worth, I haven't run into undesirable behavior since the PR, so it should be okay user-experience wise. Although, I'd like to include the ability to get an entire copy-deep paste of a score which includes the title frames and any footer frames

**Pull request merged**
