### PR TITLE
MusicXML: Add support for part-name-display

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Backport of #22322

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@rettinghaus any idea why I seem to need that 2nd commit (and still need to fix a couple mtests, but there I believe I know why)

**Comment by rettinghaus** [comment]
Does it crash without the additional check? Looking at the code I have no clue.

**Comment by Jojo-Schmitz** [comment]
No, it just fails the mtests miserable, would requite lots of then to get changes, to get these new `part-name-display` added. Apparently not needed in master, that's what confuses me

**Comment by Jojo-Schmitz** [comment]
You can now see the tests before my 2nd commit

**Comment by rettinghaus** [comment]
I was actually expecting something like this either, but the tests ran green on master. Something fishy with the test runs? I'll investigate that further.

**Comment by rettinghaus** [comment]
On my branch weirdly it says: 

>No tests were found!!!

**Pull request merged**
