### PR TITLE
[Emmentaler Font] Fix headless PDF output of treble clef

### LINKED ISSUE #416: Emmentaler needs slight fixing since 3.0
As posted over @ https://musescore.org/en/node/300603#comment-1237079, there's the "headless" problem

image upon viewing a pdf in some viewers (evince, xreader...)

Fix coming up

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves:  #416 

Since this is a binary difference, I'll explain the change: took a while with trial+error, but **OS/2 Metrics** were the culprit. 

Using FontForge upon _mscore.ttf_ from 3.6.2 branch:
Emmentaler3 6 2

Whereas after checking the font (where the issue doesn't manifest) in version 2.3.2 pre-SMuFL conversion, these are the values:
Emmentaler2 3 2-2

Applying the highlighted difference to be in accord with the 2.3.2 version's values seems to fix the issue over here. To verify, using a PDF reader such as Evince/Xreader should do it.
Should be able to forward port over to 4.x also supposing there weren't any changes since 2020 or whenever it was.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
What puzzles me it that this is no 'code' change at all going along with it, not to `mscore.sfd` nor to `genttf`?

**Comment by Jojo-Schmitz** [comment]
Also I don't seem to be able to reproduce the issue, using Evince for Windows and 3.6.2?:
image

**Comment by worldwideweary** [comment]
I merely generated the font in Font Forget, and the result doesn't provide any additional changes in git history. Do you think there should be some extra steps performed? I can try saving a spline database file, but not sure that it would be required. I get a huge list of difference if I do so, and figured it wasn't necessary

**Comment by Jojo-Schmitz** [comment]
And changes to genfft that may get the same result?

**Comment by worldwideweary** [comment]
Could be a linux thing only... or Windows different from Linux/Mac. Not sure. I've had the issue since 3.0 though. Evince version 42.3 over here or Xreader 4.0.2. Maybe they use different backends.... like my evince doesn't mention popler but that it's for Gnome

**Comment by Jojo-Schmitz** [comment]
My son can't reproduce either, on Linux, using Evince and Satura

**Comment by Jojo-Schmitz** [comment]
[emmentaler-clef-2.3.2.pdf](https://github.com/Jojo-Schmitz/MuseScore/files/14976046/emmentaler-clef-2.3.2.pdf)
[emmentaler-clef-3.6.2.pdf](https://github.com/Jojo-Schmitz/MuseScore/files/14976053/emmentaler-clef-3.6.2.pdf)
[emmentaler-clef-4.2.1.pdf](https://github.com/Jojo-Schmitz/MuseScore/files/14976045/emmentaler-clef-4.2.1.pdf)

**Comment by worldwideweary** [comment]
Font Forget ™ Heck I like.

 I can add a commit with a saved sfd file but the differences seem so huge that it reminds me of like Qt Creator changing all sorts of things in a .ui from an older version, even though nothing really changed from the user's perspective. Either way, with just the ttf change from the OS/2 Metric change,  i can't reproduce the problem on my linux machine, and figured I'd menition it. The Ascent was going over the 1024 em before hand (It seemed ilke that was the reason, as all the other fonts are "within bounds" of their em Spacing after checking:

image

**Comment by worldwideweary** [comment]
Interesting... I wonder what the difference is. Do you happen to know the distribution/version? 

image

image

Those are the versions I'm running shown from Synaptic Package manager

**Comment by worldwideweary** [comment]
Using one of your PDFs, I get for 4.2.1:
image

yet again for your 2.3.2 file it is fine:
image

**Comment by Jojo-Schmitz** [comment]
And to be clear: it not that I don't believe and trust you, I'd just like to understand ;-)

**Pull request merged**
