### PR TITLE
MusicXML: system dividers and line thickness import/export

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Backport of #19696

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@rettinghaus any idea about the remaining mtest differences, the rather large differences in textLayout?
3.7:
image
4.2:
image

**Comment by rettinghaus** [comment]
Dunno. General layout overhaul in 4? Adjusting to the returned values  from the mtest should do the trick though.

**Comment by Jojo-Schmitz** [comment]
It will sure fix the mtest, question though is whether I screwed up something in my backport

**Comment by rettinghaus** [comment]
I don't see anything wrong there.

**Comment by Jojo-Schmitz** [comment]
OK, thanks for checking

**Pull request merged**
