### PR TITLE
Fix GH#145: Crash going from page to continuous view and then clicking on score element

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #145
2nd attempt, after #146 failed, resp. caused #150

### CODE REVIEW

**Comment by worldwideweary** [comment]
Hm, this still seems to cause the problem the other guy mentioned with the footers not working right

It seems like the problem is that Mu4 has things like `resetExplicitParent` and `text->moveToDummy();` ability which the MS3 codebase does not, but I might be wrong. Looks like that function some how makes the parent be attached to a "dummy" element founded in the score itself and not the page.... and Mu4 doesn't have the crash related to what i was getting in "3.7"... I'll see if I can figure something out there

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm confused now (again), does this change fix your issue or is it no longer needed?

**Comment by Jojo-Schmitz** [comment]
That `converterMode` to `unrollRepeats`chage is entrirely unrelated.
Reverting your `(Page*)this` to (`0`) change was needed to prevent #130

**Comment by Jojo-Schmitz** [comment]
The question is whether your issue https://github.com/Jojo-Schmitz/MuseScore/issues/145 still exists and whether that one-line change of mine does any good?

**Comment by worldwideweary** [comment]
if all things were the same as they were at the moment of my posting the issue, and the only change from then was that there was `setParent(nullptr);` after the layout as this PR has it, yes, it will fix the issue.

**Comment by worldwideweary** [comment]
So long as #146 is reverted, should be good to go.

**Comment by Jojo-Schmitz** [comment]
It is. This he is merged now

**Pull request merged**
