### PR TITLE
Fix GH#177: Ornaments get lost on Mu4 import

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #177

### CODE REVIEW

**Comment by HeinzVo** [comment]
Could not see any improvement with that fix on #176 and #177 so long.

**Comment by Jojo-Schmitz** [comment]
For me it does import Mu4 ornaments, like trill and short trill

**Comment by Jojo-Schmitz** [comment]
Esp. I do see those from your sample score

**Comment by HeinzVo** [comment]
Yes, now with the new release MuseScore-3.7.0.6282437472-x86_64 #176 and #177 work. Congratulations.

**Comment by Jojo-Schmitz** [comment]
That was a quite easy fix.

**Comment by Jojo-Schmitz** [comment]
See also #15705

**Pull request merged**
