### PR TITLE
Fix GH#174: Staff Texts Style Expression - Import from MS4 failed

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #174

### CODE REVIEW

**Comment by HeinzVo** [comment]
Release MuseScore-3.7.0.6349812570-x86_64 tested.
It resolves the "import" of Staff Texts with Style Expression (they are present now, that's great), but not fully the positioning ("Automatic placement flag" always turned on, so manual offsets do not have effect). Also "Minimum distance" and "Placement" default flag changed.
Is there a way to catch the state of "Automatic placement flag" too?
[MuseScore 3 Evolution_Staff Text position (automatic flag) when imported from MS4.1.1.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12764769/MuseScore.3.Evolution_Staff.Text.position.automatic.flag.when.imported.from.MS4.1.1.zip)

**Comment by HeinzVo** [comment]
It seems, that it already get lost during import to MS4 ...

**Comment by HeinzVo** [comment]
I guess all the three green/red marked flags get lost at the import to MS4. It's difficult to say, because the UI in MS4 is very unhandy, complicate and confusing (not all parameters are shown together or not shown at all and there are so many sub-sub-menus to open first).
Import from MS3.6.2 to 3.7:
MuseScore 3 Evolution_Staff Text position (automatic flag) when imported from MS3 6 2 (marked)
Import from MS3.6.2 to MS4.1 and then back to 3.7:
MuseScore 3 Evolution_Staff Text position (automatic flag) when imported from MS4 1 1 (marked)

**Comment by Jojo-Schmitz** [comment]
Autoplace setting gets lost (actually: gets set to on) on Mu3 import in Mu4 already. So something to report at https://github.com/musescore/MuseScore/issues/new/choose

The offsets are kept though and do survive the roundtrip.

**Comment by HeinzVo** [comment]
An other small thing I found now is lost positioning "below/above" of staff text expression when imported from MS4 (and in MS4 that behavior is present and correct).
See "Gloria_in_D-major_Vivaldi-RV589" page 41 measure 45.
[MuseScore 3 Evolution_Staff Text position reset to above when imported from MS4.1 (marked).zip](https://github.com/Jojo-Schmitz/MuseScore/files/12774696/MuseScore.3.Evolution_Staff.Text.position.reset.to.above.when.imported.from.MS4.1.marked.zip)

**Comment by Jojo-Schmitz** [comment]
Ah,I see, seems it is because for staff text the default position is above (Mu3 expression style or not), but for Expression in Mu4 it is below, so Expression set to above is kept as that, but Expression set to below is not, instead in Mu3 it falls back to the staff text default of above

**Comment by HeinzVo** [comment]
I'm always surprised, what all you find out!
It seems to be a really hard job to take care of just everything for any element...

**Comment by Jojo-Schmitz** [comment]
I guess that's why this downwards compatibility has never been done in the past ;-)

**Comment by HeinzVo** [comment]
My understanding of reading any element properties is about like that:
When importing/reading properties of an element, in general the effective desired or just actually set property value always should have priority to read, independent of any default value or flag. Default values anyway may be changed or toggled by pressing the "set to default" or "S" button and therefore should not influence the real and actual setted value.
After importing a value it then optionally may be checked, if it maches the currently stored default value only for gray out the values, flags or knobs.
What's your understanding about this matter?

**Comment by HeinzVo** [comment]
My understanding of reading any element properties is about like that:
When importing/reading properties of an element, in general the effective desired or just actually set property value always should have priority to read, independent of any default value or flag. Default values anyway may be changed or toggled by pressing the "set to default" or "S" button and therefore should not influence the real and actual setted value.
After importing a value it then optionally may be checked, if it maches the currently stored default value only for gray out the values, flags or knobs.
What's your understanding about this matter?

**Comment by Jojo-Schmitz** [comment]
I'm still looking into this.

Currently it seems I broke the entire Mu4 import :-(

**Comment by Jojo-Schmitz** [comment]
I'm still looking into this and trying to iunderstand the logic behind it.

Currently it seems I broke the entire Mu4 import :-(

Mu3's Expression text is Staff text, but with custom placement of below (as taken from the palette, not by global style, that S button, as that'd move all staff texts to below) and a custome text style of italic.
Mu4's Expression text is a text of its owm, with a style default of below and italic.
We now need to convert that into staff text in italic with a custom placement of below, unless we're having a Mu4 Expression text with a custom plament of above. or non-italic...

**Comment by Jojo-Schmitz** [comment]
Ah, I need my style setting PR as the basis...

**Comment by Jojo-Schmitz** [comment]
So in Mu4 we have
```xml
          <Expression>
            <text>Expression below</text>
            </Expression>
 ```
and 
```xml
          <Expression>
            <placement>above</placement>
            <minDistance>0.4</minDistance>
            <snapToDynamics>0</snapToDynamics>
            <offset x="-1" y="-1.5"/>
            <text>Expression above</text>
            </Expression>
 ```
while in Mu3 we need
```xml
          <StaffText>
            <style>Expression</style>
            <placement>below</placement>
            <text>Expression below</text>
            </StaffText>
```
resp.
```xml
          <StaffText>
            <style>Expression</style>
            <text>Expression above</text>
            </StaffText>
 ```

**Comment by Jojo-Schmitz** [comment]
OK, I got it now...

**Comment by Jojo-Schmitz** [comment]
Fixed as part ot #196

**Comment by Jojo-Schmitz** [comment]
The loss of Autoplace has now been reported upstream, see #19627

**Comment by Jojo-Schmitz** [comment]
See also #15705

**Pull request merged**
