### PR TITLE
On Mu4 import change some Mu4 style defaults to their Mu3 counterparts

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@HeinzVo please test this one too, with this your scores should look almost the same after the Mu4 roundtrip.
Only exception seems some custom stretch values for some measures, so far it seems they get lost in Mu4 already

**Comment by Jojo-Schmitz** [comment]
Can you try again please with [MuseScore_x64_6352615310](https://github.com/Jojo-Schmitz/MuseScore/suites/16705254971/artifacts/954627303)? Had a couple stupic copy/paste errors...

**Comment by HeinzVo** [comment]
Yes, Square brackets are perfectly now. Very good.
(The point with the lost ornament offsets is an other thematic, I guess)

**Comment by Jojo-Schmitz** [comment]
Might be worth a separate issue. If it isn't Mu4 loosing it already

**Comment by HeinzVo** [comment]
I do not report issues to MS4, since that seems a hopeless endeavor to ever be solved under other many many thousands of very big issues in the next 10 years. If I start to find bugs in MS4, then I should report an other thousand of new issues which costs too much time for me now.
I hope we can go on with MS3.6 and MS3.7 for the next couple of years so far.

**Comment by Jojo-Schmitz** [comment]
I can fix it for 3.7 only if it got fixed in Mu4 first

**Comment by Jojo-Schmitz** [comment]
So if you wamt it fixed in 3.7, report it against Mu4, als it won't happen

**Comment by Jojo-Schmitz** [comment]
@HeinzVo : Please test again

**Comment by HeinzVo** [comment]
Tested release MuseScore-3.7.0.6357893344-x86_64:
Most of it looks very good. The only thing I found is lost positioning "below/above" of staff text when imported from MS4 (and in MS4 that behavior is present and correct).
Set "below" when imported from MS3.6.2:
MuseScore 3 Evolution_Staff Text position below when imported from MS3 6 2 (marked)
Reset to "above" when imported from MS4.1:
MuseScore 3 Evolution_Staff Text position reset to above when imported from MS4 1 (marked)

**Comment by Jojo-Schmitz** [comment]
I haven't changed anything on those individual style settings though, so this PR should be innocent here.

**Comment by Jojo-Schmitz** [comment]
But thanks for testing

**Comment by Jojo-Schmitz** [comment]
Not really, as the fix for that is included

**Comment by Jojo-Schmitz** [comment]
Well, maybe yes. See comment there

**Comment by Jojo-Schmitz** [comment]
The loss or ornament offsets has now been reported upstream, see #19628

**Pull request merged**
