### PR TITLE
MSCZ Mu4 Compatibility Style Fix

### LINKED ISSUE #447: Importing MU4 scores looses all style settings
The style settings are read, from score_style.css, but apparently not taken into effect

Results in e.g. Jazz-style scores to loose their style, but also score in concert pitch to loose that setting
Esp. the latter is a quite critical problem.

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #447

Not sure if it fixes it entirely, but, from over here I've got it working with Title style etc, so check it out.
You could say there's "extra" changes in here that don't matter (style) but it's because it made it easier for me to test things at the start of looking into the problem. I left a comment at the end mentioning what the main change

### CODE REVIEW

**Comment by worldwideweary** [comment]
And, of course, I misspelled compatibility in the comments

**Comment by worldwideweary** [comment]
Well, looks like it's not working with the tests... so maybe I did something off here, but it is working for me on the local machine.

**Comment by Jojo-Schmitz** [comment]
It isn't just failing tests, also crashes

**Comment by worldwideweary** [comment]
If you would, pass me a Mu4 file you're using so I can check out the crash too.

**Comment by Jojo-Schmitz** [comment]
It crashes on some of the mtests

**Comment by worldwideweary** [comment]
Ah, now opening up MS3 scores I see a bunch of unknown statements etc . I'll check it out later. Hopefully the idea though helps

**Comment by Jojo-Schmitz** [comment]
Thanks a lot!

**Pull request merged**
