### PR TITLE
[CMD: up/down chord] Traverse as list after range selection

### PR DESCRIPTION
**Pull request by worldwideweary**
See issue: #606 
Testing welcome of course

Edit: this functionality was bound up with more than I thought from personal build.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I tried to port this to Mu4, got pretty far, but then got stuck at your changes to scoreview.cpp
Check https://github.com/Jojo-Schmitz/MuseScore/tree/Improvement-UpDownChord, maybe you can come up with the needed remaining changes?

**Comment by worldwideweary** [comment]
Is there something specific that was a problem? I consolidated the two functions of "up-chord" and "down-chord" into a lambda since their code was like 97% equivalent, then updated them to use the "beat precedence" moveAlt instead of upAlt and downAlt (without removing the up/downAlt functions) and then should be good to go. I'll take a look at the MS4 codebase sometime though and see if I can see why it might be problematic (haven't looked in there in a while)

**Comment by worldwideweary** [comment]
OK. I don't have a MSS4 build here but:

/src/notation/internal/notationinteraction.cpp

```cpp
void NotationInteraction::moveChordNoteSelection(MoveDirection d)
{
    IF_ASSERT_FAILED(MoveDirection::Up == d || MoveDirection::Down == d) {
        return;
    }

    EngravingItem* current = selection()->element();
    if (!current || !(current->isNote() || current->isRest())) {
        return;
    }

    EngravingItem* chordElem;
-    if (d == MoveDirection::Up) {
-        chordElem = score()->upAlt(current);
-    } else {
-       chordElem = score()->downAlt(current);
-    }
+   chordElem = score()->moveAlt(current, d);

    if (chordElem == current) {
        return;
    }

    select({ chordElem }, SelectType::SINGLE, chordElem->staffIdx());
    showItem(chordElem);
}
```
Actually, you could throw the lambda [traverseChord] and the other lambda in that definition, or declare them as regular functions/methods along with where "moveAlt" was. Hopefully that makes sense

**Comment by worldwideweary** [comment]
I just typed something up without any building or anything, but it might help I'll see if I can push against your thing you mentioned

**Comment by Jojo-Schmitz** [comment]
See #24400

**Pull request merged**
