### PR TITLE
free disk space for MacOS CI compilation

### PR DESCRIPTION
**Pull request by AntonioBL**
Trying to solve the packaging problem with Qt5.15.2

Some softwares of the virtual machine not directly used for the compilation were deleted.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [ ] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Done 😉

**Comment by AntonioBL** [comment]
Thank you :smiley: 
There was a compilation problem due to dependencies overwriting in HomeBrew. It was not caused by my modifications, but probably by a very recent HomeBrew update.
I tried a workaround similar to the one used before.

**Comment by Jojo-Schmitz** [comment]
As I'm currently away from my computer, I'll check all this when I'm back, on the weekend probably

**Comment by Jojo-Schmitz** [comment]
Oops. I needed to approve again, done now

**Comment by AntonioBL** [comment]
Ok, now everything should be solved.
The real change is the size of the (virtual) disk unit set by `hdiutil`. Then I left the instructions reclaiming some ("real") disk space (it can be useful) and I patched the compilation after the updates of HomeBrew.

...Well, workflows have to be approved again :sweat_smile: , but the resulting artifact _should_ work ok.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, the problem that #93 tries to fix by downdrading Qt...

**Pull request merged**
