### PR TITLE
Fix GH#145: Crash going from page to continuous view and then clicking on score element

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #145

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Darn, the linux build, esp. the mtests, run out of disk space

**Comment by worldwideweary** [comment]
Oh that's too bad about disk-space.

Yes, that's right. To be a little "correct" also, you could change out since it's the same code from same situation

 
`libmscore/page.cpp`:
```cpp
void Page::drawHeaderFooter(QPainter* p, int area, const QString& ss) const
```
has the line:
```cpp
text->setParent(0);
```
and the 0 could become `nullptr`. But that's just "modern" correction

The crash is rare, but when it happens, it's *weird* to solve..nullptr
It happens when getting pagePos from

```cpp
      bool Element::contains(const QPointF& p) const
      {
      return shape().contains(p - pagePos());
      }
```

at the code that reads:
```cpp
 else {
            if (parent()->parent())
                  p += parent()->pagePos();
            }
```

where parent() would end up being this text pointer that had a parent (page pointer) passing the nullptr check but then has no actual member functions set up properly or something like that and crashes on the pagePos() call. Difficult to find.

**Comment by worldwideweary** [comment]
Oh, hey by the way for example:

https://musescore.com/user/2660886/scores/6026988 if you download that score and then load it up, select an element in page view, then switch to continuous view and click around the first systems' notes... it should be easier to reproduce the crash I'm getting as an example

**Comment by Jojo-Schmitz** [comment]
Doesn't reproduce with that score for me either

**Comment by Jojo-Schmitz** [comment]
@worldwideweary please check #150, I guess this change here cause that.

**Pull request merged**
