### PR TITLE
Fix GH#22344: calculate divisions and duration using Fractions

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Backport of #22977

Resolves: [musescore#22344](https://www.github.com/musescore/MuseScore/issues/22344)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@lvinken any idea why my backport to Mu3 fails some mtests. but passes the ones you added/modified?

**Comment by lvinken** [comment]
Will check

**Comment by Jojo-Schmitz** [comment]
I believe I've found it. let's see what is says now

**Comment by Jojo-Schmitz** [comment]
Ok, better, the FB test now work, but tuplet9 still fails

**Comment by lvinken** [comment]
Test files tuplet9 are totally different in 3.7 and 4.4 dev. The 3.7 version has rounding errors, which I suspect are corrected on import, leading to different output.

**Comment by Jojo-Schmitz** [comment]
Ah, thanks! I've now copied the Mu4 tuplet9 and moved the Mu3 tuplet9 to tuplets10 and amended it, maybe you'd like to use it in your PR too

**Comment by Jojo-Schmitz** [comment]
Opps. merged a bit early...

**Pull request merged**
